services:
  web:
    image: simpledjangoapp
    container_name: django_container
    build: .
    environment:
      MYSQL_DB: dockerdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
      MYSQL_PORT: 3306
#    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:5000"
    ports:
      - "5000:8080"
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql_container
    environment:
#      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockerdb
      MYSQL_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - app-network

networks:
  app-network: